# This workflow will install Deno and run `deno lint` on a stable Ubuntu build.

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix: 
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Run Lint
        run: deno lint

      - name: Run Tests
        run: deno test -A